### ISSUE TITLE
OCSP is blocked

### ISSUE THREAD

**Issue by varistov** [nickspaargaren/no-amazon#2]
You shouldn't block OCSP used to check revocation status of certificates used by HTTPS. 
ocsp.sca1b.amazontrust.com
ocsp.rootg2.amazontrust.com
ocsp.rootca1.amazontrust.com

Imposes a serious security issue if sites that use certificate from Amazon Trust is not able to check its revocation status of the certificate that they use

**Comment by PoorPocketsMcNewHold** [comment]
I’ll suppose we'll remove those from the main list, but we will still keep listing those on a separate optional domain list still for those users who want to block all contacts at all costs.

Our list already break many website assets due to the high extent of the list, so something like that was to be expected.

Thanks for noticing us of that!
